# Generated by Django 5.2.15 on 2026-06-20 12:29

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('columns', wagtail.fields.StreamField([('column', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок колонки'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Якорь (#pool), относительный (/news/) или полный URL', 'label': 'Ссылка'}), 3: ('wagtail.blocks.StructBlock', [[('label', 1), ('url', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Ссылки'}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('links', 4)]], {})}, verbose_name='Колонки')),
                ('copyright', models.CharField(default='© 2019–2026 LP Crew. Все права защищены.', max_length=255, verbose_name='Копирайт')),
                ('legal_links', wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Якорь (#pool), относительный (/news/) или полный URL', 'label': 'Ссылка'}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {})}, verbose_name='Юридические ссылки')),
            ],
            options={
                'verbose_name': 'Подвал',
            },
        ),
        migrations.CreateModel(
            name='NavSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Якорь (#pool), относительный (/news/) или полный URL', 'label': 'Ссылка'}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {})}, verbose_name='Пункты меню')),
                ('cta_label', models.CharField(default='Записаться', max_length=60, verbose_name='CTA — текст')),
                ('cta_url', models.CharField(default='#join', max_length=255, verbose_name='CTA — ссылка')),
            ],
            options={
                'verbose_name': 'Меню (шапка)',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='LP Crew', max_length=60, verbose_name='Название бренда')),
                ('brand_mark', models.CharField(default='≈', max_length=8, verbose_name='Знак бренда')),
                ('meta_description', models.TextField(blank=True, default='LP Crew. Команда пловцов-любителей из Ханты-Мансийска.', verbose_name='Meta description (по умолчанию)')),
                ('contact_email', models.EmailField(blank=True, default='dolphin-90@yandex.ru', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='Ледовая ул. 1, Ханты-Мансийск', max_length=255, verbose_name='Адрес')),
                ('vk_url', models.CharField(blank=True, max_length=255, verbose_name='ВКонтакте')),
                ('telegram_url', models.CharField(blank=True, max_length=255, verbose_name='Telegram')),
                ('whatsapp_url', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Сайт (контакты/мета)',
            },
        ),
    ]
