# Generated by Django 5.2.15 on 2026-06-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hd_loc',
            field=models.CharField(blank=True, default='64°N · Ханты-Мансийск', max_length=80, verbose_name='Координаты в шапке'),
        ),
    ]
