# Generated by Django 5.2.15 on 2026-06-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('messenger', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('vk', 'ВКонтакте')], default='telegram', max_length=20, verbose_name='Мессенджер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('handled', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
