# Generated by Django 5.2.15 on 2026-06-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meters',
            field=models.PositiveIntegerField(blank=True, help_text='Дистанция из мини-игры «Заплыв», если заявка пришла из неё', null=True, verbose_name='Результат игры, м'),
        ),
    ]
